version: '3.9'
services:
  db:
    image: mysql:8.0.22
    container_name: copy_sync_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      PRODUCTION: 'true'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - './db/dev/mysql:/var/lib/mysql'
  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass "$REDIS_PASSWORD"
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - './db/redis:/data'
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    restart: always
